spring:
  application:
    name: auth-service
  profiles:
    active: local
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/commkart
    username: commkart-user
    password: postgres
  jpa:
    hibernate.ddl-auto: none
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.net
    port: 465
    username: apikey
    password: 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
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.net
  cloud:
    loadBalancer:
      ribbon:
        enabled: false
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
    healthcheck:
      enabled: true
